name: Publish Latest Docker Image

on:
  push:
    branches:
      - master

jobs:
  publish:
    uses: ./.github/workflows/publish-docker.yml
    secrets: inherit
    with:
      ref: master
      tag: latest